GROQ_TRANSCRIPTION_MODEL = "whisper-large-v3-turbo"
GROQ_WHISPER_COST_PER_SECOND = 0.04 / 3600

GEMINI__TRANSLATION_MODEL = "gemini-3.1-pro-preview"
GEMINI_TRANSLATION_INPUT_COST_PER_M = 2
GEMINI_TRANSLATION_OUTPUT_COST_PER_M = 12

GEMINI_ARTICLE_MODEL = "gemini-3.1-pro-preview"
GEMINI_ARTICLE_INPUT_COST_PER_M = 2
GEMINI_ARTICLE_OUTPUT_COST_PER_M = 12
