GROQ_TRANSCRIPTION_MODEL = "whisper-large-v3-turbo"
GROQ_WHISPER_COST_PER_SECOND = 0.04 / 3600

GEMINI_MODEL = "gemini-2.5-flash"
GEMINI_FLASH_INPUT_COST_PER_M = 0.075
GEMINI_FLASH_OUTPUT_COST_PER_M = 0.30

GEMINI_ARTICLE_MODEL = "gemini-3-flash-preview"
GEMINI_ARTICLE_INPUT_COST_PER_M = 0.5
GEMINI_ARTICLE_OUTPUT_COST_PER_M = 3
